// Template-based Privacy Policy / Terms of Service / Refund Policy
// generator. This produces a reasonable starting draft for a small
// dropshipping store, not legal advice — the UI and every generated
// document say so explicitly. There's no AI/randomness here on purpose:
// legal documents should be predictable and reviewable, not "generated
// content" in the same sense as the marketing copy tools.

import type { Lang } from "./i18n";

export interface PolicyInputs {
  businessName: string;
  domain: string;
  contactEmail: string;
  country: string;
  returnWindowDays: number;
  processingDays: number;
}

const today = () => new Date().toISOString().slice(0, 10);

export function generatePrivacyPolicy(i: PolicyInputs, lang: Lang): string {
  const biz = i.businessName || (lang === "en" ? "the Store" : "Магазин");
  if (lang === "en") {
    return `PRIVACY POLICY
Last updated: ${today()}

This Privacy Policy explains how ${biz} ("we", "us") collects, uses, and shares information when you visit or make a purchase from ${i.domain || "our website"}.

1. INFORMATION WE COLLECT
- Contact information you provide (name, email, shipping address, phone number) when placing an order or contacting us.
- Order information (products purchased, order value, order history).
- Payment information — processed directly by our payment provider; we do not store full card numbers on our servers.
- Device and usage information (IP address, browser type, pages viewed) collected automatically via cookies and similar technologies.

2. HOW WE USE YOUR INFORMATION
- To process and fulfill your orders, including sharing your shipping address with our fulfillment/shipping partners.
- To communicate with you about your order, respond to inquiries, and provide customer support.
- To improve our website and product offering, and, where you have consented, to send marketing communications.
- To detect and prevent fraud.

3. THIRD PARTIES WE SHARE DATA WITH
- Payment processors (e.g. Stripe, PayPal) to process payments.
- Shipping and fulfillment partners to deliver your order.
- Analytics providers (e.g. Google Analytics) and advertising platforms (e.g. Meta Pixel, TikTok Pixel) if enabled on this store.
We do not sell your personal information.

4. COOKIES
We use cookies and similar technologies to keep your cart working, remember preferences, and understand how visitors use our site. You can control cookies through your browser settings.

5. DATA RETENTION
We retain order and account information for as long as needed to fulfill orders, comply with tax/accounting obligations, and resolve disputes.

6. YOUR RIGHTS
Depending on where you live, you may have the right to access, correct, or delete your personal information, or to object to certain processing. Contact us at ${i.contactEmail || "our contact email"} to exercise these rights.

7. CHILDREN'S PRIVACY
This store is not directed at children under 16, and we do not knowingly collect personal information from children.

8. CHANGES TO THIS POLICY
We may update this policy from time to time. Changes will be posted on this page with an updated "Last updated" date.

9. CONTACT US
Questions about this policy? Contact us at ${i.contactEmail || "our contact email"}.

---
This document is a template starting point generated by Shopyfy and is NOT legal advice. Review it with a qualified lawyer before publishing, especially if you sell to customers in the EU/UK (GDPR), California (CCPA), or other jurisdictions with specific privacy law requirements.`;
  }

  return `ПОЛИТИКА КОНФИДЕНЦИАЛЬНОСТИ
Последнее обновление: ${today()}

Настоящая Политика конфиденциальности описывает, как ${biz} («мы») собирает, использует и передаёт информацию при посещении сайта ${i.domain || "нашего сайта"} и оформлении заказа.

1. КАКУЮ ИНФОРМАЦИЮ МЫ СОБИРАЕМ
- Контактные данные, которые вы предоставляете (имя, email, адрес доставки, телефон) при оформлении заказа или обращении к нам.
- Информация о заказе (купленные товары, сумма заказа, история заказов).
- Платёжная информация — обрабатывается напрямую платёжным провайдером; мы не храним полные номера карт на своих серверах.
- Информация об устройстве и использовании сайта (IP-адрес, тип браузера, просмотренные страницы), собираемая автоматически через cookie и аналогичные технологии.

2. КАК МЫ ИСПОЛЬЗУЕМ ИНФОРМАЦИЮ
- Для обработки и выполнения ваших заказов, включая передачу адреса доставки нашим партнёрам по логистике.
- Для связи с вами по поводу заказа, ответов на вопросы и поддержки.
- Для улучшения сайта и ассортимента, а также — при наличии согласия — для рассылки маркетинговых сообщений.
- Для выявления и предотвращения мошенничества.

3. КОМУ МЫ ПЕРЕДАЁМ ДАННЫЕ
- Платёжным системам (например, Stripe, PayPal) для обработки платежей.
- Партнёрам по доставке и логистике для доставки заказа.
- Сервисам аналитики (например, Google Analytics) и рекламным платформам (например, Meta Pixel, TikTok Pixel), если они подключены на этом сайте.
Мы не продаём вашу персональную информацию.

4. COOKIE
Мы используем cookie и аналогичные технологии для работы корзины, запоминания настроек и анализа поведения посетителей. Вы можете управлять cookie в настройках браузера.

5. ХРАНЕНИЕ ДАННЫХ
Мы храним информацию о заказах и аккаунте столько, сколько необходимо для выполнения заказов, соблюдения налоговых/бухгалтерских требований и разрешения споров.

6. ВАШИ ПРАВА
В зависимости от вашей юрисдикции у вас может быть право на доступ, исправление или удаление своих персональных данных, а также на возражение против определённой обработки. Свяжитесь с нами по адресу ${i.contactEmail || "нашей контактной почты"}, чтобы воспользоваться этими правами.

7. ДАННЫЕ ДЕТЕЙ
Этот сайт не предназначен для детей младше 16 лет, и мы сознательно не собираем персональные данные детей.

8. ИЗМЕНЕНИЯ В ПОЛИТИКЕ
Мы можем обновлять эту политику время от времени. Изменения будут опубликованы на этой странице с обновлённой датой.

9. КОНТАКТЫ
Вопросы по этой политике? Свяжитесь с нами: ${i.contactEmail || "наша контактная почта"}.

---
Этот документ — стартовый шаблон, сгенерированный Shopyfy, и НЕ является юридической консультацией. Проверьте его у квалифицированного юриста перед публикацией, особенно если вы продаёте покупателям в ЕС/Великобритании (GDPR) или других юрисдикциях со специфическими требованиями к защите данных.`;
}

export function generateTermsOfService(i: PolicyInputs, lang: Lang): string {
  const biz = i.businessName || (lang === "en" ? "the Store" : "Магазин");
  if (lang === "en") {
    return `TERMS OF SERVICE
Last updated: ${today()}

Welcome to ${i.domain || "our store"}, operated by ${biz}. By accessing or using this site, you agree to these Terms of Service.

1. ORDERS & PRICING
Prices are listed in USD (or your local currency, if shown) and may change without notice. We reserve the right to refuse or cancel any order, including for suspected fraud or pricing errors.

2. SHIPPING & DELIVERY
Orders are typically processed within ${i.processingDays || 2} business day(s). Some products may ship directly from third-party suppliers, which can mean longer delivery windows than orders shipped from local stock — estimated delivery times are shown at checkout and are not guaranteed.

3. RETURNS & REFUNDS
See our Refund Policy for details on our ${i.returnWindowDays || 30}-day return window.

4. INTELLECTUAL PROPERTY
All content on this site (text, images, logos) is owned by ${biz} or its licensors and may not be used without permission.

5. LIMITATION OF LIABILITY
To the maximum extent permitted by law, ${biz} is not liable for any indirect, incidental, or consequential damages arising from your use of this site or its products.

6. GOVERNING LAW
These terms are governed by the laws of ${i.country || "the jurisdiction where the business is registered"}, without regard to conflict-of-law principles.

7. CHANGES TO THESE TERMS
We may update these terms at any time; continued use of the site after changes constitutes acceptance.

8. CONTACT US
Questions? Contact us at ${i.contactEmail || "our contact email"}.

---
This document is a template starting point generated by Shopyfy and is NOT legal advice. Review it with a qualified lawyer before publishing.`;
  }

  return `УСЛОВИЯ ИСПОЛЬЗОВАНИЯ
Последнее обновление: ${today()}

Добро пожаловать на сайт ${i.domain || "нашего магазина"}, который управляется ${biz}. Используя этот сайт, вы соглашаетесь с настоящими Условиями использования.

1. ЗАКАЗЫ И ЦЕНЫ
Цены указаны в USD (или в вашей местной валюте, если она отображается) и могут изменяться без предварительного уведомления. Мы оставляем за собой право отказать в заказе или отменить его, в том числе при подозрении на мошенничество или ошибку в цене.

2. ДОСТАВКА
Заказы обычно обрабатываются в течение ${i.processingDays || 2} рабочего(их) дня. Некоторые товары могут отправляться напрямую от сторонних поставщиков, что может означать более долгий срок доставки, чем при отправке со склада — ориентировочные сроки доставки указаны при оформлении заказа и не гарантированы.

3. ВОЗВРАТЫ И ВОЗМЕЩЕНИЯ
Подробности — в нашей Политике возврата (окно возврата ${i.returnWindowDays || 30} дней).

4. ИНТЕЛЛЕКТУАЛЬНАЯ СОБСТВЕННОСТЬ
Весь контент на этом сайте (тексты, изображения, логотипы) принадлежит ${biz} или её лицензиарам и не может использоваться без разрешения.

5. ОГРАНИЧЕНИЕ ОТВЕТСТВЕННОСТИ
В максимально допустимой законом степени ${biz} не несёт ответственности за любые косвенные или случайные убытки, возникшие в связи с использованием сайта или его товаров.

6. ПРИМЕНИМОЕ ПРАВО
Настоящие условия регулируются законодательством ${i.country || "юрисдикции регистрации бизнеса"}.

7. ИЗМЕНЕНИЯ УСЛОВИЙ
Мы можем обновлять эти условия в любое время; продолжение использования сайта после изменений означает согласие с ними.

8. КОНТАКТЫ
Вопросы? Свяжитесь с нами: ${i.contactEmail || "наша контактная почта"}.

---
Этот документ — стартовый шаблон, сгенерированный Shopyfy, и НЕ является юридической консультацией. Проверьте его у квалифицированного юриста перед публикацией.`;
}

export function generateRefundPolicy(i: PolicyInputs, lang: Lang): string {
  const biz = i.businessName || (lang === "en" ? "the Store" : "Магазин");
  const days = i.returnWindowDays || 30;
  const processing = i.processingDays || 2;
  if (lang === "en") {
    return `REFUND & RETURN POLICY
Last updated: ${today()}

We want you to be happy with your order from ${biz}. Here's how returns and refunds work.

1. RETURN WINDOW
You have ${days} days from the date of delivery to request a return.

2. CONDITION
Items must be unused, in their original packaging, and in the same condition you received them, unless the item arrived damaged or defective.

3. HOW TO START A RETURN
Email us at ${i.contactEmail || "our contact email"} with your order number and reason for return. We'll confirm the return address and next steps.

4. DAMAGED OR DEFECTIVE ITEMS
If your item arrived damaged or defective, contact us within ${days} days with photos — we'll arrange a replacement or full refund at no cost to you.

5. REFUNDS
Once we receive and inspect your return, we'll process your refund to the original payment method within ${processing} business day(s). It may take a few additional days for your bank to post it.

6. NON-RETURNABLE ITEMS
Final-sale, personalized, or intimate/hygiene items may not be eligible for return — this will be noted on the product page.

7. CONTACT US
Questions about a return? Email ${i.contactEmail || "our contact email"}.

---
This document is a template starting point generated by Shopyfy and is NOT legal advice. Return/refund requirements vary by jurisdiction and payment processor — review this with a qualified lawyer before publishing.`;
  }

  return `ПОЛИТИКА ВОЗВРАТА
Последнее обновление: ${today()}

Мы хотим, чтобы вы остались довольны заказом в ${biz}. Вот как работают возвраты и возмещения.

1. СРОК ВОЗВРАТА
У вас есть ${days} дней с даты доставки, чтобы запросить возврат.

2. СОСТОЯНИЕ ТОВАРА
Товар должен быть неиспользованным, в оригинальной упаковке и в том же состоянии, в котором вы его получили — за исключением случаев, когда товар пришёл повреждённым или бракованным.

3. КАК ОФОРМИТЬ ВОЗВРАТ
Напишите нам на ${i.contactEmail || "нашу контактную почту"}, указав номер заказа и причину возврата. Мы подтвердим адрес возврата и дальнейшие шаги.

4. ПОВРЕЖДЁННЫЕ ИЛИ БРАКОВАННЫЕ ТОВАРЫ
Если товар пришёл повреждённым или бракованным, свяжитесь с нами в течение ${days} дней с фотографиями — мы организуем замену или полный возврат средств бесплатно для вас.

5. ВОЗМЕЩЕНИЕ СРЕДСТВ
После получения и проверки возврата мы вернём средства на исходный способ оплаты в течение ${processing} рабочего(их) дня. Зачисление на счёт может занять у банка ещё несколько дней.

6. ТОВАРЫ, НЕ ПОДЛЕЖАЩИЕ ВОЗВРАТУ
Товары финальной распродажи, персонализированные или гигиенические товары могут не подлежать возврату — это будет указано на странице товара.

7. КОНТАКТЫ
Вопросы по возврату? Напишите на ${i.contactEmail || "нашу контактную почту"}.

---
Этот документ — стартовый шаблон, сгенерированный Shopyfy, и НЕ является юридической консультацией. Требования к возврату средств различаются в зависимости от юрисдикции и платёжной системы — проверьте документ у квалифицированного юриста перед публикацией.`;
}
