import type { Request, Response } from "express";
import { getPromoCode, markRedeemed } from "../promoStore.js";
import { issueEntitlementToken } from "../entitlement.js";

// POST /api/promo/redeem { code }
// The only way a frontend gets an entitlement token — requires a promo
// code that was actually generated by the Stripe webhook after a real
// payment. Redemption is intentionally idempotent (the same rightful
// owner can redeem the same code again from a second device/browser); it
// is not a one-time-use token.
export async function redeemPromoCode(req: Request, res: Response) {
  const code = String(req.body?.code ?? "").trim().toUpperCase();
  if (!code) {
    return res.status(400).json({ error: "code is required." });
  }

  const entry = await getPromoCode(code);
  if (!entry) {
    return res.status(404).json({ error: "Invalid promo code." });
  }

  await markRedeemed(code);
  const token = issueEntitlementToken(entry.plan, entry.email);
  res.json({ plan: entry.plan, email: entry.email, token });
}
